language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
env:
  - YTDL_TEST_SET=core
  - YTDL_TEST_SET=download
  - TESTS=regression_core
  - TESTS=regression_download
matrix:
  fast_finish: true
  allow_failures:
    - env: YTDL_TEST_SET=download

script: devscripts/travis.sh
notifications:
  email:
  # TODO: change before merge to put back project members !
    - anisse@astier.eu
