language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
env:
  - TESTS=complete
  - TESTS=regression_1-of-7
  - TESTS=regression_2-of-7
  - TESTS=regression_3-of-7
  - TESTS=regression_4-of-7
  - TESTS=regression_5-of-7
  - TESTS=regression_6-of-7
  - TESTS=regression_7-of-7
  - YTDL_TEST_SET=core
  - YTDL_TEST_SET=download
matrix:
  allow_failures:
    - env: TESTS=complete
    - env: YTDL_TEST_SET=download

script: devscripts/travis.sh
before_script:
  - chmod +x ./devscripts/run_tests.sh
notifications:
  email:
  # TODO: change before merge to put back project members !
    - anisse@astier.eu
#  irc:
#    channels:
#      - "irc.freenode.org#youtube-dl"
#    skip_join: true
