language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
install:
  - bash ./devscripts/install_srelay.sh
  - export PATH=$PATH:$(pwd)/tmp/srelay-0.4.8b6
env:
  - TESTS=complete
  - TESTS=regression_1-of-7
  - TESTS=regression_2-of-7
  - TESTS=regression_3-of-7
  - TESTS=regression_4-of-7
  - TESTS=regression_5-of-7
  - TESTS=regression_6-of-7
  - TESTS=regression_7-of-7
matrix:
  allow_failures:
    - env: TESTS=complete

script: devscripts/travis.sh
notifications:
  email:
  # TODO: change before merge to put back project members !
    - anisse@astier.eu
#  irc:
#    channels:
#      - "irc.freenode.org#youtube-dl"
#    skip_join: true
